version: 2
jobs:
  build:
    working_directory: ~/to-do-app
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.4.25-ram
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo apt update
      - run: sudo apt install postgresql-client-9.4
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-test-requirements
      - run: 
          name: Setup test database
          command: |
            . venv/bin/activate
            source dbsetup.sh
            alembic upgrade head 
          environment:
            USER: postgresql://postgres@localhost/postgres
            TDA_DB: postgresql://todoapp_user:tdapp8@localhost/todoapp_test  
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - setup_remote_docker