version: 2
jobs:
  build:
    working_directory: ~/to-do-app
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-test-requirements
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
