version: 2
jobs:
  build:
    working_directory: ~/to-do-app
    docker:
      - image: circleci/python:3.6.4
              
      - image: circleci/postgres:9.6.16-alpine-ram
        environment:
          TDA_DB_USER: todoapp_user
          TDA_DB_TEST: postgresql://todoapp_user:tdapp8@localhost/todoapp_test
      
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo apt-get search postgres-client
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          psql \
            -c "CREATE ROLE todoapp_user PASSWORD 'tdapp8' CREATEDB CREATEROLE LOGIN;" 
            -c "GRANT CREATE, CONNECT, TEMP ON DATABASE todoapp_devel, todoapp_test TO todoapp_user;"
      - run: |
          psql \
            -d $TDA_DB_TEST \
            -c "CREATE TABLE users (id int NOT NULL, name varchar(80), passwordhash varchar(255), useremail varchar(80), PRIMARY KEY(id));
            -c "INSERT INTO users VALUES(1, 'denchik', 'pbkdf2:sha256:150000\$wHwsgiLd\$6979f267446c0e3d2797c21006f9272c3e19d5c70925d87989983ab3826350d8', 'capuldis@gmail.com');"
            -c "SELECT * FROM users;"    
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-test-requirements
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
