version: 2
jobs:
  build:
    working_directory: ~/to-do-app
    docker:
      - image: circleci/python:3.6.4
        environment:
          PG_USER_DB: postgresql://postgres@localhost/circle_test
          TDA_DB: postgresql://todoapp_user:tdapp8@localhost/todoapp_test
              
      - image: circleci/postgres:9.4.25-ram
      
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo apt update
      - run: sudo apt install postgresql-client-9.4
      - run: whoami
      - run: |
          psql \
            -d $PG_USER_DB \
            -c "CREATE DATABASE todoapp_test;"
      - run: |
          psql \
            -d $PG_USER_DB \
            -c "CREATE USER todoapp_user WITH CREATEDB CREATEROLE PASSWORD 'tdapp8';"
      - run: |
          psql \
            -d $PG_USER_DB \
            -c "GRANT CREATE, CONNECT, TEMP ON DATABASE todoapp_test TO todoapp_user;"
      - run: |
          psql \
            -d $TDA_DB \
            -c "CREATE TABLE users (id int NOT NULL, name varchar(80), passwordhash varchar(255), useremail varchar(80), PRIMARY KEY(id));"
      - run: |
          psql \
            -d $TDA_DB \
            -c "INSERT INTO users VALUES(1, 'denchik', 'pbkdf2:sha256:150000\$wHwsgiLd\$6979f267446c0e3d2797c21006f9272c3e19d5c70925d87989983ab3826350d8', 'capuldis@gmail.com');"
      - run: |
          psql \
            -d $TDA_DB \
            -c "SELECT * FROM users;"    
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-test-requirements
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - setup_remote_docker